Kirill.shuravin homework3
eugene-okulik/roxelstone pull request #14
Opened 2024-04-21 21:05 UTC by roxelstone

Welcome back, homework 3 ready!

2024-04-21 21:21 UTC, roxelstone commented
Homework_4_here!

2024-04-22 14:40 UTC, eugene-okulik requested changes
Третье задание :+1:

2024-04-22 14:40 UTC, eugene-okulik commented on homework/kirill_shuravin/homework_3.py
> +country = person[4]
В питоне не рекомендуется обращаться к элементам списка по индексам. В любой такой ситуации, нужно стараться этого избежать. И во здесь можно этого избежать с помощью распаковки, о которой я рассказывал в видео.

2024-04-22 14:40 UTC, eugene-okulik commented on homework/kirill_shuravin/homework_3.py
> +release_third_result = int(third_result) + 10
Заморочка этого задания в том, чтобы найти в этой строке число, каким бы оно там ни было. Для этого нужно найти в этих строках что-то одинаковое: количество символов перед числом разное; количество символов в числе тоже разное. Но есть в структуре всех строк что-то одинаковое и на это можно опереться.  
Ну и тебя должно было смутить, что ты не воспользовался методом `index`, а в задании указано, что нужно им воспользоваться.

2024-04-22 20:10 UTC, roxelstone commented on homework/kirill_shuravin/homework_3.py
> +release_third_result = int(third_result) + 10
ох я понял, я вообще не так делал)

2024-04-22 20:16 UTC, roxelstone reviewed
test

2024-04-25 07:17 UTC, eugene-okulik approved these changes

2024-04-25 07:17 UTC, merged